<?xml version='1.0' encoding='UTF-8' standalone='yes' ?>
<!-- Generated by zdocs (docrefs.py needs-tag) from needs.json. Do not edit. -->
<tagfile>
  <compound kind="requirement">
    <id>SD-REQ-001</id>
    <title>Sealing on initialisation</title>
    <filename>detailed.html</filename>
  </compound>
  <compound kind="requirement">
    <id>SD-REQ-002</id>
    <title>Argument validation</title>
    <filename>detailed.html</filename>
  </compound>
  <compound kind="requirement">
    <id>SD-REQ-003</id>
    <title>Pure verification</title>
    <filename>detailed.html</filename>
  </compound>
  <compound kind="requirement">
    <id>SD-REQ-004</id>
    <title>In-place repair under mutual exclusion</title>
    <filename>detailed.html</filename>
  </compound>
  <compound kind="requirement">
    <id>SD-REQ-005</id>
    <title>Validated read</title>
    <filename>detailed.html</filename>
  </compound>
  <compound kind="requirement">
    <id>SD-REQ-006</id>
    <title>Atomic sealed write</title>
    <filename>detailed.html</filename>
  </compound>
  <compound kind="requirement">
    <id>SD-REQ-007</id>
    <title>Transactional read-modify-write</title>
    <filename>detailed.html</filename>
  </compound>
  <compound kind="requirement">
    <id>SD-REQ-008</id>
    <title>Mutator contract enforcement</title>
    <filename>detailed.html</filename>
  </compound>
  <compound kind="requirement">
    <id>SD-REQ-009</id>
    <title>Single-copy fault recovery</title>
    <filename>detailed.html</filename>
  </compound>
  <compound kind="requirement">
    <id>SD-REQ-010</id>
    <title>Double-fault detection</title>
    <filename>detailed.html</filename>
  </compound>
  <compound kind="requirement">
    <id>SD-REQ-011</id>
    <title>Configurable unrecoverable-fault reaction</title>
    <filename>detailed.html</filename>
  </compound>
  <compound kind="requirement">
    <id>SD-REQ-012</id>
    <title>Integrity-event statistics</title>
    <filename>detailed.html</filename>
  </compound>
  <compound kind="requirement">
    <id>SD-REQ-013</id>
    <title>Fault-handler registration and event reporting</title>
    <filename>detailed.html</filename>
  </compound>
  <compound kind="requirement">
    <id>SD-REQ-014</id>
    <title>Bounded lock acquisition</title>
    <filename>detailed.html</filename>
  </compound>
  <compound kind="requirement">
    <id>SD-REQ-015</id>
    <title>No ISR-context locking</title>
    <filename>detailed.html</filename>
  </compound>
  <compound kind="requirement">
    <id>SD-REQ-016</id>
    <title>Serialised access — no torn snapshots</title>
    <filename>detailed.html</filename>
  </compound>
  <compound kind="requirement">
    <id>SD-REQ-017</id>
    <title>Integrity-mechanism self-test</title>
    <filename>detailed.html</filename>
  </compound>
  <compound kind="requirement">
    <id>SD-REQ-018</id>
    <title>Write may not silently mask corruption</title>
    <filename>detailed.html</filename>
  </compound>
  <compound kind="requirement">
    <id>SD-REQ-019</id>
    <title>Compile-time payload guards</title>
    <filename>detailed.html</filename>
  </compound>
  <compound kind="requirement">
    <id>SD-REQ-020</id>
    <title>Reduced API surface at the Strict level</title>
    <filename>detailed.html</filename>
  </compound>
  <compound kind="requirement">
    <id>SD-REQ-021</id>
    <title>Scoped access block</title>
    <filename>detailed.html</filename>
  </compound>
  <compound kind="requirement">
    <id>SD-REQ-022</id>
    <title>Unchecked commit</title>
    <filename>detailed.html</filename>
  </compound>
</tagfile>
