"""Verification suite for the checks of the proof verifier that need the package alone.

Each function below realizes one test specification (``SEG-TS-nnn``) and
demonstrates the software requirement named in its ``:verifies:`` marker. The
tests call the library as ``affirmatrix.proof.verify(package)`` and read the
named checks of its report. The name ``verify`` is read inside the test
bodies only, so this module collects before the code carries it. The
verifier is not strict about tampers it does not claim to catch, so each
tamper test also states which checks stay passed.

A package is generated by the tool over the frozen evidence (``seal``). Each
tamper changes one thing in a private copy in ``tmp_path`` and never the
shared fixture. The tests that need a design edge to change reseal the root
with the recipe of the tutorial, written again in the helper module, so that
only the changed thing differs. The golden package (``golden_evidence``) was
sealed before packages listed run bundles: it serves as the legacy package.
"""

from __future__ import annotations

from pathlib import Path

from .evidence_support import GOLDEN
from .proof_verify_support import (
    PACKAGE_CHECKS,
    case_copy,
    copy_package,
    edit,
    flip_digit,
    golden_copy,
    independent_root,
    library_verify,
    read,
    seal,
    statuses,
    with_other_hash,
    without_event,
)


def _verify(package: Path, **options):
    from affirmatrix import proof

    return proof.verify(package, **options)


def _failed(report) -> set[str]:
    return {name for name, status in statuses(report).items() if status == "failed"}


def test_the_design_root_of_a_package_is_recomputed_and_equals_the_recorded_root(
    tmp_path: Path, capsys
) -> None:
    """The verifier recomputes the design root of a package and reports that it equals the record.

    A package generated over the frozen evidence records a root. The recipe
    of the tutorial, written again in the test from the node hashes, the
    design edges, the scope and the revision of the design consistency proof,
    gives the same value. The verifier reports the check named root as
    passed. The golden package, which was sealed before packages listed run
    bundles, records the root in the golden file; the recipe gives that value
    too, and the verifier passes the root, the identity, the agreement and the
    unblocked checks of it. The verifier needs no configuration, no case and
    no run bundle for these checks.

    :verifies: SEG-SREQ-237
    :test-id: SEG-TS-119
    """
    sealed = seal(tmp_path, capsys)
    recorded = read(sealed.package, "design_consistency_proof")["root"]
    assert independent_root(sealed.package) == recorded
    report = _verify(sealed.package)
    assert statuses(report)["root"] == "passed"

    golden = golden_copy(tmp_path)
    expected = (GOLDEN / "design_root.txt").read_text(encoding="utf-8").strip()
    assert read(golden, "design_consistency_proof")["root"] == expected
    assert independent_root(golden) == expected
    legacy = statuses(_verify(golden))
    assert {name: legacy[name] for name in PACKAGE_CHECKS} == dict.fromkeys(
        PACKAGE_CHECKS, "passed"
    )


def test_a_changed_design_root_input_fails_the_root_check(tmp_path: Path, capsys) -> None:
    """The verifier reports the root check as failed when one input of the root changed.

    Four private copies of a generated package each change one input of the
    root in the design consistency proof, and nothing else: one hexadecimal
    digit of a node hash, a design edge removed, the revision, and the
    scope. The root recorded in each copy is the original. For each copy the
    check named root is failed. For the first two copies it is the only
    check that fails. An untouched copy passes the root check.

    :verifies: SEG-SREQ-237
    :test-id: SEG-TS-120
    """
    sealed = seal(tmp_path, capsys)
    assert statuses(_verify(sealed.package))["root"] == "passed"

    def digit(body: dict) -> None:
        node = body["nodeManifest"][0]
        node["hash"] = flip_digit(node["hash"])

    def edge(body: dict) -> None:
        body["designEdges"].pop()

    def revision(body: dict) -> None:
        body["revision"] = "2" * 40

    def scope(body: dict) -> None:
        body["scope"] = body["scope"][:1]

    for label, tamper, alone in (
        ("digit", digit, True),
        ("edge", edge, True),
        ("revision", revision, False),
        ("scope", scope, False),
    ):
        copy = copy_package(sealed.package, tmp_path, label)
        edit(copy, "design_consistency_proof", tamper)
        report = _verify(copy)
        assert statuses(report)["root"] == "failed", label
        if alone:
            assert _failed(report) == {"root"}, label


def test_documents_that_disagree_on_what_the_package_is_fail_the_identity_check(
    tmp_path: Path, capsys
) -> None:
    """The verifier reports the identity check as failed when two documents name different packages.

    In a generated package the evidence manifest and the design consistency
    proof agree on the snapshot identifier, the requested scope and the
    revision: the check named identity is passed. Three private copies each
    change one of the three in the evidence manifest only: another snapshot
    identifier, one requested requirement removed, another revision. For each
    copy the identity check is failed, and the root check is still passed.

    :verifies: SEG-SREQ-238
    :test-id: SEG-TS-121
    """
    sealed = seal(tmp_path, capsys)
    assert statuses(_verify(sealed.package))["identity"] == "passed"

    def snapshot(body: dict) -> None:
        body["snapshotId"] = body["snapshotId"][:-1] + (
            "0" if body["snapshotId"][-1] != "0" else "1"
        )

    def scope(body: dict) -> None:
        body["requestedScope"] = body["requestedScope"][:1]

    def revision(body: dict) -> None:
        body["revision"] = "2" * 40

    for label, tamper in (
        ("snapshot", snapshot),
        ("scope", scope),
        ("revision", revision),
    ):
        copy = copy_package(sealed.package, tmp_path, label)
        edit(copy, "evidence_manifest", tamper)
        found = statuses(_verify(copy))
        assert found["identity"] == "failed", label
        assert found["root"] == "passed", label


def test_an_outcome_or_finding_outside_the_member_scope_fails_the_agreement_check(
    tmp_path: Path, capsys
) -> None:
    """The verifier reports the agreement check as failed for a name that is no member of the scope.

    In a generated package every outcome and every finding that the execution
    coverage record and the coverage report name is a member of the member
    scope of the evidence manifest: the check named agreement is passed.
    Two private copies each break that. In the first, one outcome of the
    execution coverage record is removed from the member scope. In the
    second, the coverage report holds one more finding about a name that is
    no member. For each copy the agreement check is failed and the root check is
    still passed.

    :verifies: SEG-SREQ-239
    :test-id: SEG-TS-122
    """
    sealed = seal(tmp_path, capsys)
    assert statuses(_verify(sealed.package))["agreement"] == "passed"
    outcome = read(sealed.package, "execution_coverage_record")["outcomes"][0]["id"]

    def drop_member(body: dict) -> None:
        body["memberScope"].remove(outcome)

    def stranger(body: dict) -> None:
        body["diagnostics"].append(
            {
                "condition": "outcome was skipped",
                "detail": "",
                "severity": "info",
                "subject": "no-such-run/NO_SUCH_TEST",
            }
        )

    for label, document, tamper in (
        ("member", "evidence_manifest", drop_member),
        ("finding", "coverage_report", stranger),
    ):
        copy = copy_package(sealed.package, tmp_path, label)
        edit(copy, document, tamper)
        found = statuses(_verify(copy))
        assert found["agreement"] == "failed", label
        assert found["root"] == "passed", label


def test_records_that_disagree_on_set_aside_skipped_or_excused_outcomes_fail_the_agreement_check(
    tmp_path: Path, capsys
) -> None:
    """The verifier reports the agreement check as failed when the record and the report differ.

    In a generated package the execution coverage record and the coverage
    report agree on which outcomes are set aside, skipped and excused. Three
    private copies each break one of the three. In the first, an outcome that
    the record holds is also listed as stale in the report. In the second, an
    outcome that the report lists as skipped has the result passed in the
    record. In the third, the report lists as excused an outcome that carries
    no waiver in the record. For each copy the check named agreement is
    failed.

    :verifies: SEG-SREQ-239
    :test-id: SEG-TS-123
    """
    sealed = seal(tmp_path, capsys)
    record = read(sealed.package, "execution_coverage_record")
    report = read(sealed.package, "coverage_report")
    fresh = next(o["id"] for o in record["outcomes"] if o["result"] == "passed")
    skipped = report["skippedOutcomes"][0]

    def stale(body: dict) -> None:
        body["staleOutcomes"].append(fresh)

    def excused(body: dict) -> None:
        body["excusedOutcomes"].append(fresh)

    def not_skipped(body: dict) -> None:
        for outcome in body["outcomes"]:
            if outcome["id"] == skipped:
                outcome["result"] = "passed"

    for label, document, tamper in (
        ("stale", "coverage_report", stale),
        ("skipped", "execution_coverage_record", not_skipped),
        ("excused", "coverage_report", excused),
    ):
        copy = copy_package(sealed.package, tmp_path, label)
        edit(copy, document, tamper)
        assert statuses(_verify(copy))["agreement"] == "failed", label


def test_a_coverage_report_that_records_a_blocked_scope_fails_the_unblocked_check(
    tmp_path: Path, capsys
) -> None:
    """The verifier reports the unblocked check as failed when the report says the scope is blocked.

    The coverage report of a generated package records the scope as not
    blocked: the check named unblocked is passed. A private copy changes the
    one flag, as the tutorial does with a text editor, and nothing else. The
    unblocked check of the copy is failed. The root check is still passed,
    because the root does not cover the report, and the check named unblocked is
    the only check that fails.

    :verifies: SEG-SREQ-240
    :test-id: SEG-TS-124
    """
    sealed = seal(tmp_path, capsys)
    assert statuses(_verify(sealed.package))["unblocked"] == "passed"
    copy = copy_package(sealed.package, tmp_path, "blocked")
    edit(copy, "coverage_report", lambda body: body.update(blocked=True))

    report = _verify(copy)

    assert statuses(report)["unblocked"] == "failed"
    assert statuses(report)["root"] == "passed"
    assert _failed(report) == {"unblocked"}


def test_every_design_edge_bound_by_a_review_event_passes_the_affirmations_check(
    tmp_path: Path, capsys
) -> None:
    """The verifier reports the affirmations check as passed when the case binds every design edge.

    The case in which the package was generated holds a review event for every
    strong edge, made when the edges were affirmed. Given that case, the
    verifier reports the check named affirmations as passed for a generated
    package. Given no case, it does not make the check: the check is not made.

    :verifies: SEG-SREQ-241
    :test-id: SEG-TS-125
    """
    sealed = seal(tmp_path, capsys)

    given = statuses(library_verify(sealed.opened, sealed.package, with_case=True))
    absent = statuses(_verify(sealed.package))

    assert given["affirmations"] == "passed"
    assert absent["affirmations"] == "not made"


def test_a_design_edge_without_a_binding_review_event_fails_the_affirmations_check(
    tmp_path: Path, capsys
) -> None:
    """The verifier reports the affirmations check as failed for an edge the case does not bind.

    Two private copies of the case each change the review events of one
    design edge of the package. In the first, the one event of the edge is
    removed. In the second, the event is kept and the content hash of its
    requirement endpoint is changed by one hexadecimal digit, so that it binds
    another node hash than the package records. For each copy, given that
    case, the check named affirmations is failed and its detail names both
    endpoints of the edge. Checked against the original case, the same package
    passes.

    :verifies: SEG-SREQ-241
    :test-id: SEG-TS-126
    """
    sealed = seal(tmp_path, capsys)
    edge = read(sealed.package, "design_consistency_proof")["designEdges"][0]
    original = statuses(library_verify(sealed.opened, sealed.package, with_case=True))
    assert original["affirmations"] == "passed"

    for label, change in (
        ("removed", without_event(edge)),
        ("hash", with_other_hash(edge)),
    ):
        opened = case_copy(sealed, tmp_path, label, change)

        report = library_verify(opened, sealed.package, with_case=True)

        check = {c.name: c for c in report.checks}["affirmations"]
        assert str(check.status) == "failed", label
        assert edge["from"] in check.detail and edge["to"] in check.detail, label


def test_a_snapshot_identifier_that_is_not_the_directory_name_fails_the_identity_check(
    tmp_path: Path, capsys
) -> None:
    """The verifier fails the identity check when the identifier is not the directory name.

    A generated package, named by the path of its directory, passes the check
    named identity. A private copy of the same documents sits in a directory
    with another name. For the copy the identity check is failed, its detail
    holds both names, and the root check is still passed.

    :verifies: SEG-SREQ-264
    :test-id: SEG-TS-152
    """
    sealed = seal(tmp_path, capsys)
    assert statuses(_verify(sealed.package))["identity"] == "passed"
    stamp, fingerprint = sealed.package.name.split("-")
    other = f"{stamp}-{flip_digit(fingerprint)}"
    copy = copy_package(sealed.package, tmp_path, "renamed", name=other)

    report = _verify(copy)

    found = statuses(report)
    assert found["identity"] == "failed"
    assert found["root"] == "passed"
    detail = {c.name: c for c in report.checks}["identity"].detail
    assert sealed.package.name in detail and other in detail


def test_an_outcome_of_another_revision_fails_the_agreement_check(tmp_path: Path, capsys) -> None:
    """The verifier fails the agreement check for an outcome that carries another revision.

    In a generated package every outcome of the execution coverage record
    carries the revision of the package: the check named agreement is passed.
    A private copy gives one outcome of the record another revision, with the
    same form. For the copy the agreement check is failed and the root check
    is still passed.

    :verifies: SEG-SREQ-265
    :test-id: SEG-TS-153
    """
    sealed = seal(tmp_path, capsys)
    assert statuses(_verify(sealed.package))["agreement"] == "passed"
    copy = copy_package(sealed.package, tmp_path, "revision")

    def revision(body: dict) -> None:
        body["outcomes"][0]["revision"] = "2" * 40

    edit(copy, "execution_coverage_record", revision)

    found = statuses(_verify(copy))

    assert found["agreement"] == "failed"
    assert found["root"] == "passed"


def test_an_outcome_of_the_record_that_is_also_stale_fails_the_agreement_check(
    tmp_path: Path, capsys
) -> None:
    """The verifier fails the agreement check when a recorded outcome is also listed as stale.

    A private copy of a generated package lists in its coverage report, as
    stale, one outcome that its execution coverage record holds. For the copy
    the check named agreement is failed and the root check is still passed.
    The untouched package passes.

    :verifies: SEG-SREQ-266
    :test-id: SEG-TS-154
    """
    sealed = seal(tmp_path, capsys)
    assert statuses(_verify(sealed.package))["agreement"] == "passed"
    held = read(sealed.package, "execution_coverage_record")["outcomes"][0]["id"]
    copy = copy_package(sealed.package, tmp_path, "stale")
    edit(copy, "coverage_report", lambda body: body["staleOutcomes"].append(held))

    found = statuses(_verify(copy))

    assert found["agreement"] == "failed"
    assert found["root"] == "passed"


def test_a_member_scope_that_is_not_what_the_documents_name_fails_the_agreement_check(
    tmp_path: Path, capsys
) -> None:
    """The verifier fails the agreement check when the member scope has too much or too little.

    The member scope of a generated package is the design nodes, the outcomes
    and nothing else: the check named agreement is passed. Two private copies
    change the evidence manifest only. In the first, the member scope holds
    one name more that no document names. In the second, one design node is
    missing from the member scope. For each copy the agreement check is
    failed and the root check is still passed.

    :verifies: SEG-SREQ-267
    :test-id: SEG-TS-155
    """
    sealed = seal(tmp_path, capsys)
    assert statuses(_verify(sealed.package))["agreement"] == "passed"
    node = read(sealed.package, "design_consistency_proof")["nodeManifest"][0]["id"]

    def more(body: dict) -> None:
        body["memberScope"].append("NO-SUCH-NODE")

    def less(body: dict) -> None:
        body["memberScope"].remove(node)

    for label, tamper in (("more", more), ("less", less)):
        copy = copy_package(sealed.package, tmp_path, label)
        edit(copy, "evidence_manifest", tamper)
        found = statuses(_verify(copy))
        assert found["agreement"] == "failed", label
        assert found["root"] == "passed", label


def test_a_coverage_report_that_lists_an_unready_edge_fails_the_unblocked_check(
    tmp_path: Path, capsys
) -> None:
    """The verifier fails the unblocked check when the report lists an unready edge.

    A private copy of a generated package lists one design edge as pending in
    the unready edges of its coverage report, and keeps the flag that says
    the scope is not blocked. For the copy the check named unblocked is
    failed and the root check is still passed. The untouched package passes.

    :verifies: SEG-SREQ-268
    :test-id: SEG-TS-156
    """
    sealed = seal(tmp_path, capsys)
    assert statuses(_verify(sealed.package))["unblocked"] == "passed"
    edge = read(sealed.package, "design_consistency_proof")["designEdges"][0]
    copy = copy_package(sealed.package, tmp_path, "unready")
    edit(
        copy,
        "coverage_report",
        lambda body: body["unreadyEdges"].append({**edge, "state": "pending"}),
    )

    found = statuses(_verify(copy))

    assert found["unblocked"] == "failed"
    assert found["root"] == "passed"


def test_a_coverage_report_with_a_blocking_finding_fails_the_unblocked_check(
    tmp_path: Path, capsys
) -> None:
    """The verifier fails the unblocked check when the report holds a finding that blocks.

    A private copy of a generated package holds one more finding of severity
    error in its coverage report, about a requirement of the scope, and keeps
    the flag that says the scope is not blocked. For the copy the check named
    unblocked is failed and the root check is still passed.

    :verifies: SEG-SREQ-269
    :test-id: SEG-TS-157
    """
    sealed = seal(tmp_path, capsys)
    assert statuses(_verify(sealed.package))["unblocked"] == "passed"
    copy = copy_package(sealed.package, tmp_path, "finding")
    finding = {
        "condition": "edge is not affirmed",
        "detail": "",
        "severity": "error",
        "subject": "SD-REQ-001",
    }
    edit(copy, "coverage_report", lambda body: body["diagnostics"].append(finding))

    found = statuses(_verify(copy))

    assert found["unblocked"] == "failed"
    assert found["root"] == "passed"
