"""Verification suite for ``proof show`` and for naming and reading a package.

Each function below realizes one test specification (``SEG-TS-nnn``) and
demonstrates the software requirement named in its ``:verifies:`` marker. The
tests call the command line through ``affirmatrix.cli.main``, as an operator
would. ``proof show`` and ``proof verify`` are read inside the test bodies
only, so this module collects before the code carries them.

A package is generated by the tool over the frozen evidence into a case in
``tmp_path`` (``seal``). The expected content of ``proof show`` is read from
the four documents of the package by hand, in the helper module, and never
from the tool. The golden package serves as the legacy package: it was sealed
before packages listed run bundles.
"""

from __future__ import annotations

import json
import os
from pathlib import Path

import pytest

from affirmatrix.sources import composed

from .evidence_support import run
from .proof_verify_support import (
    copy_package,
    edit,
    expected_requirements,
    generate_more,
    golden_copy,
    read,
    seal,
    show_cli,
    verify_cli,
)


@pytest.mark.xfail(strict=True, reason="SEG-SREQ-248: proof show and proof verify do not exist yet")
def test_a_package_is_named_by_identifier_by_unique_prefix_or_by_path(
    tmp_path: Path, capsys
) -> None:
    """Proof show and proof verify accept an identifier, a unique prefix of it, or a directory path.

    A case holds one generated package. For each of the two verbs, naming the
    package by its snapshot identifier, by the first twelve characters of the
    identifier, and by the path of a copy of its directory outside the case
    gives exit status 0. For proof show the three renderings are the same
    report, and its snapshot identifier is the identifier of the package.

    :verifies: SEG-SREQ-248
    :test-id: SEG-TS-133
    """
    sealed = seal(tmp_path, capsys)
    elsewhere = copy_package(sealed.package, tmp_path, "assessor")
    names = (sealed.package.name, sealed.package.name[:12], str(elsewhere))

    reports = []
    for name in names:
        status, report = show_cli(capsys, sealed.opened, name)
        assert status == 0, name
        reports.append(report)
        status, _ = verify_cli(capsys, sealed.opened, name)
        assert status == 0, name

    assert reports[0] == reports[1] == reports[2]
    assert reports[0]["snapshotId"] == sealed.package.name


@pytest.mark.xfail(strict=True, reason="SEG-SREQ-249: proof show and proof verify do not exist yet")
def test_a_prefix_that_names_two_packages_is_refused_with_both_names(
    tmp_path: Path, capsys
) -> None:
    """Proof show and proof verify exit with status 2 for a prefix that names two packages.

    A case holds two packages generated one second apart, so that their
    identifiers share a long prefix. A prefix of both identifiers makes each
    verb exit with status 2. The output names both packages by identifier and
    holds no report. A prefix of the first identifier alone, longer
    than the shared one, names one package, and each verb exits with
    status 0.

    :verifies: SEG-SREQ-249
    :test-id: SEG-TS-134
    """
    sealed = seal(tmp_path, capsys)
    other = generate_more(sealed, capsys, "2026-10-01T00:00:01+00:00")
    shared = os.path.commonprefix([sealed.package.name, other.name])
    assert 8 <= len(shared) < len(sealed.package.name)
    unique = sealed.package.name[: len(shared) + 1]
    assert not other.name.startswith(unique)

    for verb in ("show", "verify"):
        status, out = run(capsys, "proof", verb, *sealed.opened.args(), shared)
        assert status == 2, verb
        assert sealed.package.name in out and other.name in out, verb
        status, _ = run(capsys, "proof", verb, *sealed.opened.args(), unique)
        assert status == 0, verb


@pytest.mark.xfail(strict=True, reason="SEG-SREQ-250: proof show does not exist yet")
def test_proof_show_reports_what_the_package_records_about_itself(tmp_path: Path, capsys) -> None:
    """Proof show reports the snapshot, scopes, revision, totality, root and findings.

    For a generated package, the machine-readable report of proof show holds
    the snapshot identifier, the requested scope, the member scope, the
    revision, the totality flag, the design root and the digests of the run
    bundles, each equal to what the documents of the package record, and the
    findings of the coverage report in the order of the report. The
    human-readable report holds the snapshot identifier, the revision, the
    design root, each digest and each requested requirement.

    :verifies: SEG-SREQ-250
    :test-id: SEG-TS-135
    """
    sealed = seal(tmp_path, capsys)
    manifest = read(sealed.package, "evidence_manifest")
    proof = read(sealed.package, "design_consistency_proof")
    report = read(sealed.package, "coverage_report")

    status, shown = show_cli(capsys, sealed.opened, sealed.package.name)

    assert status == 0
    assert shown["snapshotId"] == manifest["snapshotId"]
    assert shown["requestedScope"] == manifest["requestedScope"]
    assert shown["memberScope"] == manifest["memberScope"]
    assert shown["revision"] == manifest["revision"]
    assert shown["total"] == manifest["total"]
    assert shown["designRoot"] == proof["root"]
    assert shown["runBundles"] == manifest["runBundles"]
    assert shown["findings"] == report["diagnostics"]
    status, text = run(capsys, "proof", "show", *sealed.opened.args(), sealed.package.name)
    assert status == 0
    wanted = [manifest["snapshotId"], manifest["revision"], proof["root"]]
    for needle in [*wanted, *manifest["runBundles"], *manifest["requestedScope"]]:
        assert needle in text, needle


@pytest.mark.xfail(strict=True, reason="SEG-SREQ-250: proof show does not exist yet")
def test_proof_show_lists_the_specifications_outcomes_and_implementations_of_each_requirement(
    tmp_path: Path, capsys
) -> None:
    """Proof show reports, for each requirement of the scope, what the package records for it.

    For a generated package, the machine-readable report of proof show holds
    one entry for each requirement of the package's node manifest and no other
    entry. Each entry holds the requirements that refine it, the
    specifications that verify it, the implementations that implement it, and
    the outcomes (identifier and result) that confirm one of those
    specifications. The expected lists are read by hand from the design edges
    and the execution coverage record. At least one entry holds a
    skipped outcome, and at least one entry refines no requirement and holds
    no specification.

    :verifies: SEG-SREQ-250
    :test-id: SEG-TS-136
    """
    sealed = seal(tmp_path, capsys)
    expected = expected_requirements(sealed.package)

    status, shown = show_cli(capsys, sealed.opened, sealed.package.name)

    assert status == 0
    entries = {entry["id"]: entry for entry in shown["requirements"]}
    assert sorted(entries) == sorted(expected)
    for identifier, wanted in expected.items():
        entry = entries[identifier]
        assert sorted(entry["refinedBy"]) == wanted["refinedBy"], identifier
        assert sorted(entry["specifications"]) == wanted["specifications"], identifier
        assert sorted(entry["implementations"]) == wanted["implementations"], identifier
        found = sorted((o["id"], o["result"]) for o in entry["outcomes"])
        assert found == wanted["outcomes"], identifier
    results = {result for wanted in expected.values() for _, result in wanted["outcomes"]}
    assert "skipped" in results
    assert any(w["refinedBy"] and not w["specifications"] for w in expected.values())


@pytest.mark.xfail(strict=True, reason="SEG-SREQ-251: proof show does not exist yet")
def test_a_package_without_run_bundle_digests_says_that_none_is_recorded(
    tmp_path: Path, capsys
) -> None:
    """Proof show says that no run bundle digest is recorded for a package that lists none.

    The golden package was sealed before packages listed run bundles. For
    it, proof show exits with status 0, its human-readable report holds the
    words "not recorded" on the line about the run bundle digests, and its
    machine-readable report holds no digest for them. A generated package that
    lists a digest shows the digest and not those words.

    :verifies: SEG-SREQ-251
    :test-id: SEG-TS-137
    """
    sealed = seal(tmp_path, capsys)
    legacy = golden_copy(tmp_path)
    assert "runBundles" not in read(legacy, "evidence_manifest")

    status, text = run(capsys, "proof", "show", *sealed.opened.args(), str(legacy))
    assert status == 0
    digest_line = next(line for line in text.splitlines() if "run bundle" in line)
    assert "not recorded" in digest_line
    status, shown = show_cli(capsys, sealed.opened, legacy)
    assert status == 0
    assert not shown["runBundles"]

    status, text = run(capsys, "proof", "show", *sealed.opened.args(), sealed.package.name)
    digest = read(sealed.package, "evidence_manifest")["runBundles"][0]
    assert digest in text
    assert "not recorded" not in text


@pytest.mark.xfail(strict=True, reason="SEG-SREQ-252: proof show does not exist yet")
def test_proof_show_reads_no_run_bundle_and_no_current_stream(
    tmp_path: Path, capsys, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Proof show gives the same report whatever the readers of the configuration supply.

    A control call of proof show names the package with a working
    configuration. Then the producer that reads the current stream is
    replaced by one that records each call and fails, and proof show gives the
    same report and exit status 0. The producer was not called. A second
    call names a configuration whose requirement export does not exist: the
    report is the same again.

    :verifies: SEG-SREQ-252
    :test-id: SEG-TS-138
    """
    sealed = seal(tmp_path, capsys)
    control = show_cli(capsys, sealed.opened, sealed.package.name)
    assert control[0] == 0
    calls: list[str] = []

    def refuse(*args, **options):
        calls.append("from_config")
        raise AssertionError("proof show read the current stream")

    monkeypatch.setattr(composed, "from_config", refuse)
    assert show_cli(capsys, sealed.opened, sealed.package.name) == control
    assert calls == []

    broken = tmp_path / "broken" / "affirmatrix.yaml"
    broken.parent.mkdir()
    document = sealed.opened.config.read_text(encoding="utf-8")
    broken.write_text(document.replace("needs.json", "no-such-needs.json"), encoding="utf-8")
    status, out = run(
        capsys,
        "proof",
        "show",
        "--json",
        "--case",
        str(sealed.case),
        "--config",
        str(broken),
        sealed.package.name,
    )
    assert (status, json.loads(out)) == control


@pytest.mark.xfail(strict=True, reason="SEG-SREQ-253: proof show does not exist yet")
def test_proof_show_exits_with_status_0_whatever_the_package_records(
    tmp_path: Path, capsys
) -> None:
    """Proof show exits with status 0 for a package that records a blocked scope or a wrong root.

    Four packages are read. A generated package that records no problem, a
    private copy whose coverage report records the scope as blocked with a
    finding of severity error, a private copy whose recorded root is not the
    root of its design, and the golden package. For each of them proof show
    exits with status 0 and reports the package.

    :verifies: SEG-SREQ-253
    :test-id: SEG-TS-139
    """
    sealed = seal(tmp_path, capsys)

    def blocked(body: dict) -> None:
        body["blocked"] = True
        body["diagnostics"].append(
            {
                "condition": "edge is not affirmed",
                "detail": "",
                "severity": "error",
                "subject": "SD-REQ-001",
            }
        )

    wrong_root = copy_package(sealed.package, tmp_path, "root")
    edit(wrong_root, "design_consistency_proof", lambda body: body.update(root="0" * 64))
    blocked_scope = copy_package(sealed.package, tmp_path, "blocked")
    edit(blocked_scope, "coverage_report", blocked)

    for package in (sealed.package, blocked_scope, wrong_root, golden_copy(tmp_path)):
        status, shown = show_cli(capsys, sealed.opened, package)
        assert status == 0, package.name
        assert shown["requestedScope"], package.name


@pytest.mark.xfail(strict=True, reason="SEG-SREQ-254: proof show and proof verify do not exist yet")
def test_a_package_that_cannot_be_read_gives_exit_status_2(tmp_path: Path, capsys) -> None:
    """Proof show and proof verify exit with status 2 for a package that cannot be read.

    A generated package is read by each verb with exit status 0. Six
    other names each give exit status 2 and a refusal in the output: an
    identifier that the case does not hold, a path that is no directory, an
    empty directory, a copy without its coverage report, a copy whose
    evidence manifest is not JSON, and a copy whose design consistency proof
    lacks its root. The output holds no report.

    :verifies: SEG-SREQ-254
    :test-id: SEG-TS-140
    """
    sealed = seal(tmp_path, capsys)
    for verb in ("show", "verify"):
        status, _ = run(capsys, "proof", verb, *sealed.opened.args(), sealed.package.name)
        assert status == 0, verb

    plain = tmp_path / "plain-file"
    plain.write_text("not a package\n", encoding="utf-8")
    empty = tmp_path / "empty"
    empty.mkdir()
    no_report = copy_package(sealed.package, tmp_path, "no-report")
    (no_report / "coverage_report.jsonld").unlink()
    no_json = copy_package(sealed.package, tmp_path, "no-json")
    (no_json / "evidence_manifest.jsonld").write_text("{not json", encoding="utf-8")
    no_root = copy_package(sealed.package, tmp_path, "no-root")
    edit(no_root, "design_consistency_proof", lambda body: body.pop("root"))
    names = {
        "unknown identifier": "20200101T000000Z-000000000000",
        "plain file": str(plain),
        "empty directory": str(empty),
        "no report": str(no_report),
        "no json": str(no_json),
        "no root": str(no_root),
    }

    for verb in ("show", "verify"):
        for label, name in names.items():
            status, out = run(capsys, "proof", verb, *sealed.opened.args(), name)
            assert status == 2, (verb, label)
            assert out.strip(), (verb, label)
            assert "snapshot:" not in out and '"checks"' not in out, (verb, label)


def _empty_directory(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    """An empty working directory: no configuration file and no case in it."""
    empty = tmp_path / "empty"
    empty.mkdir()
    monkeypatch.chdir(empty)
    return empty


@pytest.mark.xfail(strict=True, reason="SEG-SREQ-270: proof show does not exist yet")
def test_proof_show_reads_a_package_named_by_path_with_no_configuration_and_no_case(
    tmp_path: Path, capsys, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Proof show reads a package named by its directory path from an empty directory.

    A generated package is copied to a place outside its case. The working
    directory is empty: it holds no configuration file and no case, and the
    call names neither. Given only the path of the copy, proof show exits with
    status 0 and reports the snapshot identifier of the package. The
    directory is still empty afterwards.

    :verifies: SEG-SREQ-270
    :test-id: SEG-TS-158
    """
    sealed = seal(tmp_path, capsys)
    elsewhere = copy_package(sealed.package, tmp_path, "assessor")
    empty = _empty_directory(tmp_path, monkeypatch)

    status, out = run(capsys, "proof", "show", "--json", str(elsewhere))

    assert status == 0, out
    assert json.loads(out)["snapshotId"] == sealed.package.name
    assert list(empty.iterdir()) == []
